/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as MikuRouteImport } from './routes/miku'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as IndexRouteImport } from './routes/index'

const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const MikuRoute = MikuRouteImport.update({
  id: '/miku',
  path: '/miku',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/miku': typeof MikuRoute
  '/nutrition': typeof NutritionRoute
  '/premium': typeof PremiumRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/miku': typeof MikuRoute
  '/nutrition': typeof NutritionRoute
  '/premium': typeof PremiumRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fitness': typeof FitnessRoute
  '/miku': typeof MikuRoute
  '/nutrition': typeof NutritionRoute
  '/premium': typeof PremiumRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/fitness' | '/miku' | '/nutrition' | '/premium'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/fitness' | '/miku' | '/nutrition' | '/premium'
  id: '__root__' | '/' | '/fitness' | '/miku' | '/nutrition' | '/premium'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FitnessRoute: typeof FitnessRoute
  MikuRoute: typeof MikuRoute
  NutritionRoute: typeof NutritionRoute
  PremiumRoute: typeof PremiumRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/miku': {
      id: '/miku'
      path: '/miku'
      fullPath: '/miku'
      preLoaderRoute: typeof MikuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FitnessRoute: FitnessRoute,
  MikuRoute: MikuRoute,
  NutritionRoute: NutritionRoute,
  PremiumRoute: PremiumRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
